[pytest]
testpaths = tests
addopts = -v -ra --alluredir=allure-results --clean-alluredir
markers =
    positive: позитивные сценарии
    negative: негативные сценарии
    smoke: быстрые проверки доступности страниц
filterwarnings =
    ignore::DeprecationWarning
